### ISSUE TITLE
App always writes to a `Splitwise` account regardless of config.yml entry

### ISSUE THREAD

**Issue by MaybeThisIsRu** [gcflames5/ynab-splitwise-integration#4]
The app always writes all transactions to `Splitwise` account - regardless of what I specify in `config.yml`.

I have been manually maintaining a `Splitwise` account up until stumbling this app and would love to discard the manual process should this work well. However, I would prefer archiving my `Splitwise` account and creating a new account for the app to use.

Specifying `Splitwise2` (account already exists and is empty) or `SplitwiseTwo` (account already exists and is empty) in `config.yml` as below still results in the app writing to `Splitwise`.

```
splitwise:
  consumer_key: [...]
  consumer_secret: [...]
  oauth_token_file: splitwise_token.oauth
  last_transaction_date: 20-Nov-2019 11:01:00
ynab:
  access_token: [...]
  budget_name: X's Budget
  account_name: SplitwiseTwo
```

In addition, by default, YNAB simply states `Category not needed` for each transaction when it writes to `Splitwise` by itself, ignoring the config.
For me to be able to specify a category, I need to select each entry and manually pick `Splitwise` from my list of accounts again.
